/**
 * public.companies columns used by Company Settings.
 * Kept in sync with supabase/migrations and schema.sql — do not guess names.
 */
export const COMPANY_SETTINGS_COLUMNS = [
  'id',
  'created_at',
  'name',
  'logo_url',
  'address',
  'city',
  'country',
  'postcode',
  'timezone',
  'weather_location',
  'date_format',
  'time_format',
  'week_starts_on',
  'fleet_number_prefix',
  'default_vehicle_status',
  'default_driver_role',
  'default_break_minutes',
  'overtime_after_hours',
  'overtime_mode',
  'overtime_multiplier',
  'currency',
  'round_time_minutes',
  'require_manager_approval',
  'holiday_year_start',
  'annual_leave_allowance',
  'theme',
  'compact_tables',
  'email_notifications',
  'push_notifications',
  'session_timeout_minutes',
  'require_mfa',
] as const

export type CompanySettingsColumn = (typeof COMPANY_SETTINGS_COLUMNS)[number]

/** PostgREST select list — must stay a string literal for Supabase client typing. */
export const companySettingsSelect = `
  id,
  created_at,
  name,
  logo_url,
  address,
  city,
  country,
  postcode,
  timezone,
  weather_location,
  date_format,
  time_format,
  week_starts_on,
  fleet_number_prefix,
  default_vehicle_status,
  default_driver_role,
  default_break_minutes,
  overtime_after_hours,
  overtime_mode,
  overtime_multiplier,
  currency,
  round_time_minutes,
  require_manager_approval,
  holiday_year_start,
  annual_leave_allowance,
  theme,
  compact_tables,
  email_notifications,
  push_notifications,
  session_timeout_minutes,
  require_mfa
` as const
