/**
 * Bundled DREVORA legal document manifest.
 * Generated by scripts/generate-legal-manifest.mjs — do not invent hashes by hand.
 *
 * Application text is based on the supplied DREVORA legal documents.
 * Legal document versions must be updated deliberately.
 * Material changes require a new version and hash.
 * The app does not replace external legal review.
 */

export type LegalDocumentType =
  | 'customer_terms'
  | 'dpa'
  | 'privacy_policy'
  | 'worker_terms'

export type LegalAudience = 'customer_admin' | 'worker' | 'both'

export type LegalAcceptanceRequirement = 'accept' | 'acknowledge' | 'none'

export type LegalDocumentManifestEntry = {
  type: LegalDocumentType
  title: string
  version: string
  effectiveDate: string
  audience: LegalAudience
  acceptanceRequirement: LegalAcceptanceRequirement
  sourceFile: string
  isCurrent: boolean
  contentHash: string
}

export const LEGAL_OPERATOR = {
  name: 'Aurimas Jokubaitis, trading as DREVORA',
  structure: 'Sole trader',
  address: '11 Buckenham Way, Thetford, Norfolk, IP24 1ES, United Kingdom',
  email: 'admin@drevora.uk',
  website: 'drevora.app',
} as const

export const LEGAL_DOCUMENT_MANIFEST = [
  {
    type: 'customer_terms',
    title: 'DREVORA Customer Terms & Conditions',
    version: '0.3',
    effectiveDate: '2026-08-03',
    audience: 'customer_admin',
    acceptanceRequirement: 'accept',
    sourceFile: 'customer-terms-v0.3.md',
    isCurrent: true,
    contentHash: 'd36b76b715d4c9c2d1bdf8a6fffa57dbf776052d58e44d8e89a8741762b40582',
  },
  {
    type: 'dpa',
    title: 'DREVORA Data Processing Agreement',
    version: '0.3',
    effectiveDate: '2026-08-03',
    audience: 'customer_admin',
    acceptanceRequirement: 'accept',
    sourceFile: 'dpa-v0.3.md',
    isCurrent: true,
    contentHash: '5a97632431127d9584262cf5d476f80e78e4d82022a12bd0633ed3d9d5293aaf',
  },
  {
    type: 'privacy_policy',
    title: 'DREVORA Privacy Policy',
    version: '0.4',
    effectiveDate: '2026-08-14',
    audience: 'both',
    acceptanceRequirement: 'acknowledge',
    sourceFile: 'privacy-policy-v0.4.md',
    isCurrent: true,
    contentHash: '34d658d5796236291ccb874451979a439b7dff4a97b41fcc38a2a56d3e3a3373',
  },
  {
    type: 'worker_terms',
    title: 'DREVORA Worker Terms of Use',
    version: '0.2',
    effectiveDate: '2026-08-03',
    audience: 'worker',
    acceptanceRequirement: 'accept',
    sourceFile: 'worker-terms-v0.2.md',
    isCurrent: true,
    contentHash: 'ad2dbb1793ee4abc12fb23c77db6ee5a97de9bde2d6e98cb210c753a837bc74d',
  },
] as const satisfies readonly LegalDocumentManifestEntry[]

export type LegalManifestDocument = (typeof LEGAL_DOCUMENT_MANIFEST)[number]

export function getLegalManifestEntry(
  type: LegalDocumentType,
): LegalDocumentManifestEntry {
  const entry = LEGAL_DOCUMENT_MANIFEST.find((item) => item.type === type && item.isCurrent)
  if (!entry) {
    throw new Error(`Missing current legal manifest entry for ${type}`)
  }
  return entry
}

export function getLegalManifestByHash(contentHash: string): LegalDocumentManifestEntry | undefined {
  return LEGAL_DOCUMENT_MANIFEST.find((item) => item.contentHash === contentHash)
}
