/**
 * Bundled DREVORA legal document manifest.
 * Generated by scripts/generate-legal-manifest.mjs — do not invent hashes by hand.
 *
 * Application text is based on the supplied DREVORA legal documents.
 * Legal document versions must be updated deliberately.
 * Material changes require a new version and hash.
 * The app does not replace external legal review.
 */

export type LegalDocumentType =
  | 'customer_terms'
  | 'dpa'
  | 'privacy_policy'
  | 'worker_terms'

export type LegalAudience = 'customer_admin' | 'worker' | 'both'

export type LegalAcceptanceRequirement = 'accept' | 'acknowledge' | 'none'

export type LegalDocumentManifestEntry = {
  type: LegalDocumentType
  title: string
  version: string
  effectiveDate: string
  audience: LegalAudience
  acceptanceRequirement: LegalAcceptanceRequirement
  sourceFile: string
  isCurrent: boolean
  contentHash: string
}

export const LEGAL_OPERATOR = {
  name: 'Aurimas Jokubaitis, trading as DREVORA',
  structure: 'Sole trader',
  address: '11 Buckenham Way, Thetford, Norfolk, IP24 1ES, United Kingdom',
  email: 'admin@drevora.uk',
  website: 'drevora.app',
} as const

export const LEGAL_DOCUMENT_MANIFEST = [
  {
    type: 'customer_terms',
    title: 'DREVORA Customer Terms & Conditions',
    version: '0.2',
    effectiveDate: '2026-08-01',
    audience: 'customer_admin',
    acceptanceRequirement: 'accept',
    sourceFile: 'customer-terms-v0.2.md',
    isCurrent: true,
    contentHash: '683e5e8fb1aca9bc706a3117d4bc371fc9a3911d5a8a9234e88c09a275168b8e',
  },
  {
    type: 'dpa',
    title: 'DREVORA Data Processing Agreement',
    version: '0.2',
    effectiveDate: '2026-08-01',
    audience: 'customer_admin',
    acceptanceRequirement: 'accept',
    sourceFile: 'dpa-v0.2.md',
    isCurrent: true,
    contentHash: '1f2bf8a87c60b3155cfea449e968bbabaf964adc18eb6e7574b4b9f3c8d2551b',
  },
  {
    type: 'privacy_policy',
    title: 'DREVORA Privacy Policy',
    version: '0.2',
    effectiveDate: '2026-08-01',
    audience: 'both',
    acceptanceRequirement: 'acknowledge',
    sourceFile: 'privacy-policy-v0.2.md',
    isCurrent: true,
    contentHash: 'f638026e4c4d1289fdfc87592b7e887006507c2ec313bb7cb5442abc79107597',
  },
  {
    type: 'worker_terms',
    title: 'DREVORA Worker Terms of Use',
    version: '0.1',
    effectiveDate: '2026-08-01',
    audience: 'worker',
    acceptanceRequirement: 'accept',
    sourceFile: 'worker-terms-v0.1.md',
    isCurrent: true,
    contentHash: '996d470e6de922853b3dac9c1ff610a6116cc878acc56de26c98debe43243297',
  },
] as const satisfies readonly LegalDocumentManifestEntry[]

export type LegalManifestDocument = (typeof LEGAL_DOCUMENT_MANIFEST)[number]

export function getLegalManifestEntry(
  type: LegalDocumentType,
): LegalDocumentManifestEntry {
  const entry = LEGAL_DOCUMENT_MANIFEST.find((item) => item.type === type && item.isCurrent)
  if (!entry) {
    throw new Error(`Missing current legal manifest entry for ${type}`)
  }
  return entry
}

export function getLegalManifestByHash(contentHash: string): LegalDocumentManifestEntry | undefined {
  return LEGAL_DOCUMENT_MANIFEST.find((item) => item.contentHash === contentHash)
}
