-- Ensure public.companies has every column selected/saved by Company Settings.
-- This is safe to run on databases that already have some or all columns.

alter table public.companies
  add column if not exists logo_url text,
  add column if not exists address text,
  add column if not exists city text,
  add column if not exists country text,
  add column if not exists postcode text,
  add column if not exists timezone text default 'Europe/London',
  add column if not exists weather_location text,
  add column if not exists date_format text default 'DMY',
  add column if not exists time_format text default '24-hour',
  add column if not exists week_starts_on text default 'monday',
  add column if not exists fleet_number_prefix text default '',
  add column if not exists default_vehicle_status text default 'Available',
  add column if not exists default_driver_role text default 'Driver',
  add column if not exists default_break_minutes integer default 30,
  add column if not exists paid_breaks boolean default false,
  add column if not exists overtime_after_hours numeric default 10.5,
  add column if not exists overtime_mode text default 'Manual',
  add column if not exists overtime_multiplier numeric default 1.5,
  add column if not exists currency text default 'GBP',
  add column if not exists round_time_minutes integer default 0,
  add column if not exists require_manager_approval boolean default true,
  add column if not exists holiday_year_start text default '01-01',
  add column if not exists annual_leave_allowance integer default 28,
  add column if not exists theme text default 'light',
  add column if not exists compact_tables boolean default false,
  add column if not exists email_notifications boolean default true,
  add column if not exists push_notifications boolean default false,
  add column if not exists session_timeout_minutes integer default 480,
  add column if not exists require_mfa boolean default false,
  add column if not exists saturday_overtime_enabled boolean default false,
  add column if not exists saturday_overtime_after_hours numeric default 6.0,
  add column if not exists saturday_overtime_multiplier numeric default 1.5,
  add column if not exists sunday_overtime_enabled boolean default false,
  add column if not exists sunday_overtime_after_hours numeric default 0.0,
  add column if not exists sunday_overtime_multiplier numeric default 2.0,
  add column if not exists timesheet_week_start_day text default 'monday',
  add column if not exists timesheet_week_reset_month integer default 4,
  add column if not exists timesheet_week_reset_day integer default 5,
  add column if not exists holiday_counting_method text default 'working_days',
  add column if not exists holiday_working_days text[] default array[
    'monday',
    'tuesday',
    'wednesday',
    'thursday',
    'friday'
  ]::text[];

update public.companies
set
  timezone = coalesce(timezone, 'Europe/London'),
  date_format = coalesce(date_format, 'DMY'),
  time_format = coalesce(time_format, '24-hour'),
  week_starts_on = coalesce(week_starts_on, 'monday'),
  fleet_number_prefix = coalesce(fleet_number_prefix, ''),
  default_vehicle_status = coalesce(default_vehicle_status, 'Available'),
  default_driver_role = coalesce(default_driver_role, 'Driver'),
  default_break_minutes = coalesce(default_break_minutes, 30),
  paid_breaks = coalesce(paid_breaks, false),
  overtime_after_hours = coalesce(overtime_after_hours, 10.5),
  overtime_mode = coalesce(overtime_mode, 'Manual'),
  overtime_multiplier = coalesce(overtime_multiplier, 1.5),
  currency = coalesce(currency, 'GBP'),
  round_time_minutes = coalesce(round_time_minutes, 0),
  require_manager_approval = coalesce(require_manager_approval, true),
  holiday_year_start = coalesce(holiday_year_start, '01-01'),
  annual_leave_allowance = coalesce(annual_leave_allowance, 28),
  theme = coalesce(theme, 'light'),
  compact_tables = coalesce(compact_tables, false),
  email_notifications = coalesce(email_notifications, true),
  push_notifications = coalesce(push_notifications, false),
  session_timeout_minutes = coalesce(session_timeout_minutes, 480),
  require_mfa = coalesce(require_mfa, false),
  saturday_overtime_enabled = coalesce(saturday_overtime_enabled, false),
  saturday_overtime_after_hours = coalesce(saturday_overtime_after_hours, 6.0),
  saturday_overtime_multiplier = coalesce(saturday_overtime_multiplier, 1.5),
  sunday_overtime_enabled = coalesce(sunday_overtime_enabled, false),
  sunday_overtime_after_hours = coalesce(sunday_overtime_after_hours, 0.0),
  sunday_overtime_multiplier = coalesce(sunday_overtime_multiplier, 2.0),
  timesheet_week_start_day = coalesce(timesheet_week_start_day, 'monday'),
  timesheet_week_reset_month = coalesce(timesheet_week_reset_month, 4),
  timesheet_week_reset_day = coalesce(timesheet_week_reset_day, 5),
  holiday_counting_method = coalesce(holiday_counting_method, 'working_days'),
  holiday_working_days = coalesce(
    holiday_working_days,
    array['monday', 'tuesday', 'wednesday', 'thursday', 'friday']::text[]
  );

notify pgrst, 'reload schema';
